### ISSUE TITLE
Add support for customizable ramp rate(s)

### ISSUE THREAD

**Issue by dawiyo** [upsert/lutron-caseta-pro#10]
Not sure exactly how to do this but customizable ramp rates would be awesome. I was looking through this plugin for SmartThings and they seem to have implemented it using the Pro bridge.

https://github.com/njschwartz/Lutron-Smart-Pi/blob/master/smartapps/njschwartz/lutron-caseta-service-manager.src/lutron-caseta-service-manager.groovy

**Comment by upsert** [comment]
The Home Assistant light has got you covered and they refer to it as `transition`:
https://www.home-assistant.io/components/light

It is given in seconds, e.g. `transition: 10` for a 10 second fade up or down.

Lutron also supports delay, but that is not implemented in Home Assistant so I can't really use it.
