### ISSUE TITLE
Possible to add support for custom updater component?

### ISSUE THREAD

**Issue by jwelter1971** [upsert/lutron-caseta-pro#13]
Your add on is a huge and invaluable part of my setup; thanks so much for this!  

Would it be possible to add support for the custom update tracker?  I think this is just a .json file in your GitHub repo that tracks the version change.

https://github.com/custom-components/custom_updater

**Comment by cajuncoding** [comment]
Ditto!  My home wouldn’t be the same without this component!  I still don’t know why is can’t be included as a standard component in HomeAssistant...

**Comment by upsert** [comment]
Fixed by #30.
