### ISSUE TITLE
Support pulling Integration Report directly (without relying on the app)

### ISSUE THREAD

**Issue by synthead** [upsert/lutron-caseta-pro#14]
As the component stands now, every time the bridge is programmed, the user must fetch JSON data from the app for the new configuration (as described [here](https://github.com/upsert/lutron-caseta-pro#first-time-setup)).  Although this works reliably, it is cumbersome.

Instead of pulling from the app, we should pull this data directly from the bridge.  Also, fetching the Integration Report is a quick, non-intensive process, so perhaps it would even be possible to fetch this data every time on startup.  We might be able to avoid keeping a `lutron_caseta_pro_lutron-gw.json` configuration file around this way.

**Comment by upsert** [comment]
Would love to do this but unfortunately I am not aware of any way to obtain the integration report from the hub automatically. It is available through the SSH interface after jumping through all the hoops with certificates, but this component is specifically designed to only use the Telnet interface on the pro models.

From my experience, once you have installed all the devices and the scenes are stable, there are very few changes to the report.
