### ISSUE TITLE
Pico Remote Delay to Turn Lights On

### ISSUE THREAD

**Issue by bdubsw** [upsert/lutron-caseta-pro#16]
When you use the pico remote to trigger an automation in home assistant which in turn turns lights on/off there is a noticeable delay. The delay is not found if the remote is configured to turn lights on and off via lutron bridge. It looks like the lights turn on in the GUI/Dasbhoard instantly, but the lights aren't actually turning on then. I looked at the Pico remote LED that rapidly blinks when you press a button and it seems that the lights turn on/off after it's done blinking. Not sure if maybe it's broadcasting and blocking the action to turn the lights on/off.

**Comment by upsert** [comment]
I think the default ramp up time is 1 second for Lutron lights if not specified. If you use `"transition" : 0` in your automation that will force it to the minimum that Lutron supports. Even then it will never be quite as fast as natively through Lutron. The Picos actually talk to the dimmers directly through their wireless protocol. You can test this by unplugging your hub and you'll see the Picos assigned to dimmers will still work.

I recommend programming Pico remotes to controls lights natively through Lutron if you want the fastest response time and then add automations as a bonus to trigger other things. For scene control with the 4 button Picos or in situations where a longer fade time is acceptable, it can all be done through HA. Even then, it works best if you trigger a preset light scene made in the Lutron app so you get the smooth fade in of all lights in the scene at the same time.
