### ISSUE TITLE
Multiple buttons pressed at the same time result in Sensor value getting stuck

### ISSUE THREAD

**Issue by cajuncoding** [upsert/lutron-caseta-pro#2]
It appears that the component might (or could be made to) support multiple button presses . . . which would be awesome!  However, there is an issue where if I press more than one button at the same time then the sensor value will get stuck as the value of the first button in that combination.

For example I was thinking of creating a combination of FAVORITE+OFF to send a special command via HomeAssistant to shut off my Home Theater....

When I do this, if I press OFF and hold it down while pressing FAVORITE, then the sensor value will get stuck at 4.  If i press FAVORITE (value=2) again then the resulting sensor value will be 6 (4 + 2).  This applies to any followup button presses . . . I'll get the sum of 4 plus that buttons value...

The only way to revert this is to press the OFF button by itself again which then results in the sensor value reverting back to 0 default state again, and my scripts will resume working.

A multi-button press support would be awesome and looks very feasible with the bitwise combination of the current button values (power of 2).... 

But this def. appears to be a bug, in that the base number gets left as the value of the first button pressed...

**Comment by upsert** [comment]
The pico buttons are not really designed for multiple concurrent presses and the telnet interface used by the plugin is producing this behaviour when you do these combination. Given two buttons A and B, you have to hold A, press and hold B, release A while still holding B and then release B and then you'll get this bug. On the telnet interface it is missing the signal for releasing the first button A. They don't appear to send it given the above combination.

Further if you just hold Off and press the favorite button, the telnet interface actually repeats the same button code for whatever you have held down. So the basic off + other button won't register.

I don't think I will pursue this given the limitations of the interface. Also holding buttons down can be problematic as if you hold down the favorite button it will re-program the light levels and holding down the off button for 6 seconds puts it into pairing mode.

One thing that may be possible in the future is short press versus long press. It would require recording the time between the press and release signals and having some threshold value.

And of course, you could always buy more pico remotes. 👍

**Comment by cajuncoding** [comment]
Yeah, thanks alot for looking into it a little bit and responding!

I came to similar conclusion (though with less detail info), and found that short press vs long press meets my needs really well!  You are correct in that a long press of the Favorite button might trigger updating lights, but that's not an issue if the Pico isn't linked to any lights ;-) In my use case, with no lights linked, then short vs long press adds alot of great capability.  

My use case is that, I have a pico implemented as a wall mounted dynamic volume control for my Denon reciever, that allows me to adjust volume from the Kitchen without walking across my house into the (open floor plan) Home Theater area.  It worked sooo well, I made the favorite button automatically turn on the mode for Alexa bluetooth.  I use the On/Off buttons for our favorite High/Low audio volumes, and the Up/Down buttons dynamically adjust the volume.  Then I decided I wanted to be able to turn Alex off.  So the Long press of the Favorite button does exactly that now but turning off the system.

For anyone interested (that may stumble across this thread), here's some more related details also posted here on the Volume Control and how well it works:
[https://community.home-assistant.io/t/fixed-delay-between-hass-services-call-s-in-a-python-script/21121/8?u=raerae1616](https://community.home-assistant.io/t/fixed-delay-between-hass-services-call-s-in-a-python-script/21121/8?u=raerae1616)

I implemented this with a little bit of Python script acrobatics.... and it's working well for me.  But, it would be awesome if it was in the underlying Component such that there were different numbers reported between short press and long press.

While more Pico remotes would do the trick, it also takes up more space on the wall and starts to degrage the Wife Approval Factor (which is SUPER important).  And having just a little extra flexibility here makes this a pretty amazing (as in the BEST feature of my whole automation Setup)!

[pico_denonavr_volume_switch.zip](https://github.com/upsert/lutron-caseta-pro/files/1869295/pico_denonavr_volume_switch.zip)

And, just in case anyone is interested in my implementation that is working . . . here ya go:

Python Snippet for short vs long press (FULL Python Script is attached)...
```
#NOTE: Center scene button == 2 (Center Scene Button)
elif pico_state_value == 2:
	long_press = False
	
	#Get the current Harmony remote Activity
	current_activity = hass.states.get("sensor.htpc_remote_current_activity").state

	#If we are currently off, then Turn on "Alexa Speakers"
	if current_activity == "PowerOff":
		#When the center scene button is pressed, we check and turn on Alexa Speakers mode 
		#	if the Receiver is currently Powered Off; but not if it's already on but in a different mode.
		hass.services.call("remote", "turn_on", {
			"entity_id": "remote.htpc_remote",
			"activity": "Listen to Alexa"
		})
		#IF we just powered on the Receiver then we need to wait for it to initialize!
		#NOTE: time.sleep() param is in Seconds!
		time.sleep(5)

	else:
		long_press_secs = 3  #How many seconds is a Long Press
		wait_refresh_secs = .25 #How often do we want to check for Long Press status
		wait_total_count = long_press_secs / wait_refresh_secs
		wait_counter = 0
		
		#We wait and watch for a long press...but to be responsive we check our status in short intervals until we know either
		#	if the button was released (short-press/aborting a long press), or eventually the long-press threshold is exceeded...
		#NOTE: We loop in 1 second increments to provide quick response whenever the button is released (rather than wait/block for the entire time)
		#NOTE: we need to refresh from the HASS States to know if it's still pressed
		while wait_counter < wait_total_count and int(hass.states.get("sensor.living_room_audio_pico").state) == 2: 
			wait_counter = wait_counter + 1 #NOTE: += Syntax does NOT Work!
			time.sleep(wait_refresh_secs) 	#NOTE: time.sleep() param is in Seconds!

		#After we're done watching for long press, initialize long_press based on how long the button was pressed.
		long_press = wait_counter >= wait_total_count
				
	if long_press:
		#When the center scene button is long-pressed, we will turn the entire Home Theater Off!
		hass.services.call("remote", "turn_off", { "entity_id": "remote.htpc_remote" })
	else:
		#When center button is short-pressed, we set the volume to Medium!
		hass.services.call("rest_command", "denonavr_volume_medium")
```

[pico_denonavr_volume_switch.zip](https://github.com/upsert/lutron-caseta-pro/files/1869300/pico_denonavr_volume_switch.zip)

**Comment by upsert** [comment]
Ok thanks. I will close this one up.
