### ISSUE TITLE
0.88 Breaking change for custom components

### ISSUE THREAD

**Issue by tube0013** [upsert/lutron-caseta-pro#22]
from the beta release notes:

> Note for custom component developers: We are moving to a new file structure. Platforms now live embedded in components. Custom platforms will have to be updated to follow this pattern. This is a breaking change in case your custom platform overrides a built-in platform. Rename your custom platform from, ie light/hue.py to hue/light.py.

https://rc--home-assistant-docs.netlify.com/blog/2019/02/13/release-88/

**Comment by upsert** [comment]
Fixed by 97b46b9. Tested both 0.87 and 0.88 dev and it is compatible with both.
