### ISSUE TITLE
Unable to find component ...

### ISSUE THREAD

**Issue by samandjt** [upsert/lutron-caseta-pro#23]
Hello,

I am migrating from basic smart bridge to PRO.  Previously on basic bridge everything worked.  

My setup is HA 0.84.6 (Hassbian install on Raspberry Pi)

I removed the old lutron_caseta component from my config yaml.  Then followed your instructions.

Everything seems fine until I paste the integration report.  After doing that I get 
Invalid config 
The following components and platforms could not be set up: 
• fan.lutron_caseta_pro 
• cover.lutron_caseta_pro 
• sensor.lutron_caseta_pro 
• scene.lutron_caseta_pro 
• switch.lutron_caseta_pro 
light.lutron_caseta_pro 
Please check your config. 
DISMISS 

In the logs:
Unable to prepare setup for platform sensor.lutron_caseta_pro: Platform not found.
11:08 AM setup.py (ERROR)
Unable to find component sensor.lutron_caseta_pro
11:08 AM loader.py (ERROR)
Unable to prepare setup for platform scene.lutron_caseta_pro: Platform not found.
11:08 AM setup.py (ERROR)
Unable to find component scene.lutron_caseta_pro
11:08 AM loader.py (ERROR)
Unable to prepare setup for platform light.lutron_caseta_pro: Platform not found.
11:08 AM setup.py (ERROR)
Unable to find component light.lutron_caseta_pro
11:08 AM loader.py (ERROR)
Unable to prepare setup for platform switch.lutron_caseta_pro: Platform not found.
11:08 AM setup.py (ERROR)
Unable to find component switch.lutron_caseta_pro
11:08 AM loader.py (ERROR)
Unable to prepare setup for platform cover.lutron_caseta_pro: Platform not found.
11:08 AM setup.py (ERROR)
Unable to find component cover.lutron_caseta_pro
11:08 AM loader.py (ERROR)
Unable to prepare setup for platform fan.lutron_caseta_pro: Platform not found.
11:08 AM setup.py (ERROR)
Unable to find component fan.lutron_caseta_pro
11:08 AM loader.py (ERROR)
You are using a custom component for lutron_caseta_pro which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
11:08 AM loader.py (WARNING)

The JSON seems to be created in the config folder

My folder structure:
![image](https://user-images.githubusercontent.com/26305268/53302037-0e396300-3828-11e9-9509-20790ef82e22.png)

Any help would be appreciated.

Cheers,

Sam

**Comment by upsert** [comment]
The component was updated for the breaking change in 0.88 that requires a [new file structure](https://developers.home-assistant.io/blog/2019/02/19/the-great-migration.html) with lutron_caseta_pro/light.py etc. so you may want to update to HA 0.88 or higher.

If you are not ready to upgrade and want the pre-0.88 structured component, here is the last version:
https://github.com/upsert/lutron-caseta-pro/archive/95677bc1d21a8aa459acc3649d33f6a87330906f.zip

**Comment by samandjt** [comment]
Awesome thanks.  I could not get the old structure to work, so I went ahead
an just upgraded to 0.88 :-)

Sorry I was a pester, just built my Hassbian setup (migrated from manual
install on my Synology NAS) in January and didn't think there would have
been a substantial changed.  Good lesson to check changelogs.

Can't wait to use the features of PRO, especially the pico remotes to
control other elements.

Cheers,

Sam
