### ISSUE TITLE
Pico - long press, possible?

### ISSUE THREAD

**Issue by sfnetwork** [upsert/lutron-caseta-pro#25]
Pretty sure if it doesn't work now, it's because it's not possible but we never know...
Is there any way to have long press considered as a different function than single press on the Pico remote?

**Comment by upsert** [comment]
Lutron does not have any explicit support for double press, long press etc. If you press too long on certain buttons it will go into pairing or other modes for trim adjustments. Ra2 Select also uses double press to go to 100% instead of last level.

I think some potential is there to do it based on events in HA, but I think that is better left outside of the component. There is already a lot of feature creep in this component.

**Comment by cajuncoding** [comment]
There was already some discussion on this topic here:
https://github.com/upsert/lutron-caseta-pro/issues/15#issuecomment-450537367

I implemented a very simple approach to provide short vs long press for turning my Receiver (& Bluetooth adapter to automatically connect my Amazon Echo) on/off for easy music and volume adjustment (e.g. Dimmer buttons of the pico are my volume control) . . . it made a very useful and slick Wall mounted volume control via Lutron Pico remotes.

Also some more info. on my implementation here:
https://community.home-assistant.io/t/fixed-delay-between-hass-services-call-s-in-a-python-script/21121/8?u=raerae1616

Hope this helps!

**Comment by silfa718** [comment]
I realized this is closed but I would like to integrate a dim up and down feature when long pressed from the pico remote and perhaps take advantage of the new light dimming feature in .106.

**Comment by cajuncoding** [comment]
@silfa718 here is a small sample code that I use to implement Long Press via Python Script.  It's not built in, but it works . . . hopefully this helps:

```
#Obtain status of the Pico Remote
PICO_ENTITY_ID = "sensor.living_room_audio_pico";
pico_status = hass.states.get(PICO_ENTITY_ID)
pico_state_value = int(pico_status.state)

#DEBUG Notification via Pushover
#hass.services.call("notify", "pushover", {"message": "Pico Switch Debug: [Pico={0}]".format(pico_state_value)})

#CONFIGURATION for Long Press Variables
long_press_secs = 3  #How many seconds is a Long Press
wait_refresh_secs = .25 #How often do we want to check for Long Press status
wait_total_count = long_press_secs / wait_refresh_secs

#NOTE: Center scene button == 2 (Center Scene Button)
if pico_state_value == 2:
	is_long_press = False
	wait_counter = 0
	
	#We wait and watch for a long press...but to be responsive we check our status in short intervals until we know either
	#	if the button was released (short-press/aborting a long press), or eventually the long-press threshold is exceeded...
	#NOTE: We loop in a timed increment to provide a balance between quick response whenever the button is released 
	#		and the tight loop element... htough the Python Script will copmletely block the HomeAssistant processing 
	#		thread during the sleep() time.
	#NOTE: we need to refresh from the HASS States to know if it's still pressed
	while wait_counter < wait_total_count and int(hass.states.get(PICO_ENTITY_ID).state) == pico_state_value: 
		wait_counter = wait_counter + 1
		#NOTE: time.sleep() param is in Seconds!
		time.sleep(wait_refresh_secs)

	#After we're done watching for long press, initialize long_press based on how long the button was pressed.
	is_long_press = wait_counter >= wait_total_count
				
	if is_long_press:
		#When the center scene button is long-pressed, we will turn the entire Home Theater Off!
		hass.services.call("light", "turn_on", { 
			"entity_id": "light.some_light_to_dim",
			"brightness_step_pct": 25
		})
```
