### ISSUE TITLE
Great Migration support

### ISSUE THREAD

**Issue by mofonics** [upsert/lutron-caseta-pro#29]
Noobie here so apologies if I am doing this incorrectly. I got the custom component warning in my log and attempted to update my file structure to be in accordance...but I must have missed something because I lost all of my light entities. I have tried scouring the forums for guidance but am at a dead end. Are there any instructions on how to update this truly kick@ss component?

**Comment by upsert** [comment]
Make sure you have the component updated. Refer to #23.

**Comment by Mdleal** [comment]
a manifest.json is required. 

https://developers.home-assistant.io/docs/en/creating_integration_manifest.html

**Comment by upsert** [comment]
Based on the current release 0.92.1, no changes and no manifest are required. The component is fully functional.
