### ISSUE TITLE
Auto load integration report from Ra2 Select Main Repeater

### ISSUE THREAD

**Issue by Tuckie** [upsert/lutron-caseta-pro#33]
Like how pylutron handles it: https://github.com/thecynic/pylutron/blob/4d9222c96ef7ac7ac458031c058ad93ec31cebbf/pylutron/__init__.py#L399

**Comment by upsert** [comment]
Unfortunately, the XML-based report from the Ra2 Main Repeater is not available on Ra2 Select or Caseta Smart Bridge Pro.

**Comment by Tuckie** [comment]
Yeah, I think I noticed that in another issue, however it would be nice to do this automatically when using a platform that supports it.

**Comment by upsert** [comment]
This component is only for Ra2 Select / Caseta Smart Bridge Pro so I leave it to the other integration to handle their own configuration as they see fit.
