### ISSUE TITLE
Caseta Fan Control Registered as Light Entity in HA

### ISSUE THREAD

**Issue by bnapora** [upsert/lutron-caseta-pro#52]
Added a Caseta Fan switch through the integration.  It is created in HA under the "light" domain.  
Documentation for this integration suggest it should support "fan" entity types.
Is there any thing in the Integration Report I should modify before uploading to integration to get it to work?
If any logs I should send that would be helpful I'm happy to do it.

Brian

**Comment by squirtbrnr** [comment]
Follow steps 7 and 8 of the installation steps and make sure you restart HA after changing the configuration entry where you define which ID is a fan.  After that, your fan will show up as a fan and not a light.  I just followed the steps after adding a fan to my Lutron system and had no issues and it shows as a fan on the frontend of HA.

**Comment by upsert** [comment]
Looks like a configuration issue. Closing this bug report.
