### ISSUE TITLE
Occupancy sensor

### ISSUE THREAD

**Issue by plc** [upsert/lutron-caseta-pro#53]
Any chance this integration could detect the new [Caseta Occupancy Sensor](https://www.homedepot.com/p/Lutron-Caseta-Smart-Motion-Sensor-Occupancy-Multi-location-Works-with-Alexa-and-the-Google-Assistant-White-PD-OSENS-WH/312479961)? 

Let me know if i can provide any logging or other details to best assist.

**Comment by jsb5151** [comment]
@plc if you have one, have you checked if the sensor reports its status through LIP/telnet?

I should be ordering one next week if all goes well; but if it doesn't report anything on LIP I might have to skip.  I wanted to use them for other (non-Lutron) purposes, just like my Picos.

**Comment by plc** [comment]
i have not, but i’m happy to if you want to point me in the right direction of the commands. also do you have a donation box? happy to chip in for your motion sensor, especially since i use this plugin every day!

**Comment by upsert** [comment]
The motion sensors do not generate any events on the Telnet protocol used by this component. Refer to issue #6 for the long history of updates regarding this issue.
