### ISSUE TITLE
Unable to prepare setup for platform lutron_caseta_pro.cover: Platform not found (cannot import name 'CoverEntity' from 'homeassistant.components.cover' 

### ISSUE THREAD

**Issue by DanskerUS** [upsert/lutron-caseta-pro#57]
Running 109.6 and updated to the latest version. After the update I get the error above (three times for CoverEntity, SwitchEntity and LightEntity).

Is this an update for 110 that breaks 109 ?

Thank you.

**Comment by upsert** [comment]
Sorry, just updated the component to fix #56 for Home Assistant 0.110.

Here is the old version for 0.109.x:
https://github.com/upsert/lutron-caseta-pro/archive/c455e1923e42c81568986e44dce8562d87af11c4.zip

**Comment by jsb5151** [comment]
I have the same issue; should I upgrade to .110 to fix this?

**Comment by wixoff** [comment]
My perspective: given that there are 400+ replies to the blog post announcing 0.110, I think I'm going to let that settle down a bit before upgrading.  The rollback posted by @upsert works fine for now!

**Comment by DanskerUS** [comment]
upsert, -

Thank you for the 109.x version, all works again !!!
