### ISSUE TITLE
Invalid config error after updating

### ISSUE THREAD

**Issue by pjrt** [upsert/lutron-caseta-pro#58]
I upgraded to the latest via HAC but now I'm getting this error:

![image](https://user-images.githubusercontent.com/1610164/82861275-2fd14080-9eea-11ea-8994-d4f33b4e5f40.png)

I tried reinstalling as well as removing the .json file and reloading the integration report.

**Comment by upsert** [comment]
This component requires Home Assistant 0.110.0 or higher.

Here is the old version for 0.109.x:
https://github.com/upsert/lutron-caseta-pro/archive/c455e1923e42c81568986e44dce8562d87af11c4.zip

**Comment by pjrt** [comment]
Not sure how you figured out that was the issue with what I said but yeah, that was the issue. Didn't realize there was an update. Thanks!
