### ISSUE TITLE
Read/create events for switches, dimmers and fan switches like pico remotes

### ISSUE THREAD

**Issue by DanskerUS** [upsert/lutron-caseta-pro#60]
Thank you very much for this integration, works really well. Not sure the Lutron Caseta interface provides the info, however: can switches, dimmers and fan Caseta device buttons create trigger events like a Pico remote, if so, I would sure use it.

Use case: garage light

Press on: lights come on, turn off via timer/automation in 5 minutes, for pass through
Press on again: set timer to 1 hour (or add to timer), for working in garage.

Use case: bathroom fan timer along the same line, etc.

Using this, the actual  switch, dimmer and fan Caseta device buttons can be made to function like the respective Pico.

**Comment by upsert** [comment]
The on-wall and plug-in dimmers and switches generate events in the form of light levels. They do not generate anything for the buttons themselves. So if the light level does not change, there will not be any events. Pressing the on button when a light is already on does not generate anything.

The basic use case of turning a light off after a timer can be done with automation:
Trigger type: State
Entity: <your light entity>
To: 'on'
For: HH:mm:ss

A better way to handle turning lights off in an occasionally occupied space is with an occupancy/vacancy sensor either from Lutron or other manufacturers. With occupancy it does not matter how long you spend in the space whether it is just passing through or spending time there.

For a fan timer, you could use an automation, but it may be easier to use a timer switch like Lutron MA-T51MN. They offer a configurable timer with tap once for a timer or double tap to leave it on. They also do an eco-timer version (MA-T530G) with double tap does a maximum of 30 minutes.

**Comment by DanskerUS** [comment]
Thank you for your detailed response. I suspected the interface does not generate events as I had hoped for.
