### ISSUE TITLE
Any plans to add the motion sensor?

### ISSUE THREAD

**Issue by psperry** [upsert/lutron-caseta-pro#62]
Looks like a promising product -- fast, long battery life...

https://www.amazon.com/Lutron-PD-OSENS-WH-Caseta-Occupancy-Sensor/dp/B084CMPWST/ref=sr_1_54?tag=imoreb-20&ascsubtag=UUimUdUnU63241YYwYwnb2hi4dthixs6zdvmnvwi5ldnntw6ltdn5wq

**Comment by upsert** [comment]
Unfortunately it is not supported. Refer to issue #6 for the long story.
