### ISSUE TITLE
Lutron Fan Control - fan.set_speed = low does not work

### ISSUE THREAD

**Issue by FindingJohnny** [upsert/lutron-caseta-pro#74]
I've been using the Caseta Pro integration for some time now. I recently moved and installed a number of fan controls.

They connect fine and work as expected when using the Lutron App. However, when I attempt to set the fan speed using the `fan.set_speed` service, I am unable to get the fan control to respond appropriately.

```
Service:
fan.set_speed
Payload:
entity_id: fan.master_bedroom_ceiling_fan
speed: low
```

Or speed is set medium, medium_high, high

The result is always that the fan is set to one level above the speed requested (with the exception of off. Off works as expected). So low => medium; medium => medium_high; medium_high => high; The attributes for my fans show up as follows;

```
speed_list:
  - 'off'
  - low
  - medium
  - medium_high
  - high
speed: low
integration_id: 16
area_name: Office
friendly_name: Office Ceiling Fan
supported_features: 1
```

**Comment by upsert** [comment]
Have you updated the custom component recently? Changes were contributed 4 days ago related to fan speed in pull request #73.

**Comment by FindingJohnny** [comment]
Good call. My last update was more than 4 days ago and the latest version seems to fix things. Can't believe I didn't think to check for an update. 😆 Thanks again! I'll close the issue.
