### ISSUE TITLE
This component versus the in-built Lutron component in HA

### ISSUE THREAD

**Issue by daytonturner** [upsert/lutron-caseta-pro#78]
I noticed in your README that you mention this component uses the telnet interface to do its work - which is great!

Then I went to look at the lutron module that is included in HA now, and it also seems to support the PRO bridge as well as the telnet interface for pico remotes.

Pardon my potential ignorance, but I'm just wondering if this component still provides improvement over the included Lutron HA component, and if so, what that is?

Thank you!

**Comment by upsert** [comment]
This custom component predates the existence of telnet support in the stock component in HA and it remains here for anyone that still wishes to use it. As you mentioned, it uses the telnet interface exclusively and does not use any reverse-engineered APIs or certificates extracted from the mobile app, so it could prove to be more stable if Lutron starts making changes in their other protocols.

It currently has one disadvantage in that occupancy sensor events are not exposed on the telnet interface. Only the light level changes in the associated fixtures are reported.

**Comment by daytonturner** [comment]
Got it - thank you for the clarification! I did notice their certificate hijacking in order to get it to work which is certainly a little less ideal. 

I'm not currently using the occupancy sensors, but I may just try yours out for now and cross that bridge when I get to it. Right now, I'm hoping to actually use my motion sensors from my DSC alarm instead of the lutron-native occupancy sensors, but still unsure if it will be a good approach or not.

**Comment by ryanschmidt** [comment]
I have been wondering the same. It appears this component supports picos as sensors which is handy.

**Comment by et** [comment]
Just chiming in here as someone who recently upgraded HA and noticed the built-in component....
The built-in component is nowhere near as good as this one. The built-in one thought all of my dimmers were switches so they only had on/off functionality.
It's worth it to stay on this custom component.

**Comment by jherby2k** [comment]
That's just not true! My house is full of dimmers and the official
integration works perfectly with them. Not to trash on this one or anything
- it works just fine as well.
